---
sidebar: sidebar 
permalink: task-login-copyandsync.html 
keywords: copy and sync, NetApp Copy and Sync, log in to Copy and Sync, NetApp BlueXP, BlueXP Copy and Sync, NetApp Console 
summary: Utilisez la NetApp Console pour vous connecter à NetApp Copy and Sync. 
---
= Connectez-vous à NetApp Copy and Sync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez la NetApp Console pour vous connecter à NetApp Copy and Sync.

Pour vous connecter à la Console, vous pouvez utiliser vos identifiants du site de support NetApp ou vous inscrire à une connexion cloud NetApp en utilisant votre adresse e-mail et un mot de passe. https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["En savoir plus sur la connexion"^]

NetApp Copy and Sync utilise la gestion des accès aux identités pour régir l'accès de chaque utilisateur à des actions spécifiques.

*Rôle requis dans la NetApp Console* Rôle d'administrateur de l'organisation. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console"^]

.Étapes
. Ouvrez un navigateur Web et accédez à la https://console.netapp.com/["NetApp Console"^] .
+
La page de connexion à la NetApp Console s’affiche.

. Connectez-vous à la console.
. Dans la navigation de gauche de la console, sélectionnez *Mobilité* > *Copier et synchroniser*.

